### PR TITLE
Fix colors on comment tag

### PR DESCRIPTION
**Pull request by slovenianGooner**
Fix colors to white from black on default doc comment tag.

### CODE REVIEW

**Comment by daylerees** [comment]
Hi @slovenianGooner thanks for this! I'll have to patch it back into the build process instead of merging it here or it will be overwritten. :) Can you show me a screenshot of what is effected if possible? Thanks!

**Comment by slovenianGooner** [comment]
Yeah, sure. Here it is. It is in PHPDoc comments in a class.

This is before:
screen shot 2018-01-04 at 08 05 16

And this after:
screen shot 2018-01-04 at 08 05 31

**Comment by daylerees** [comment]
Which theme is that mate? I don't think it should render like that. :)

**Comment by daylerees** [comment]
Here's my Storm for example. All themes should use a slightly lighter comment colour for the param:

http://dayle.io/0LA8zi

**Comment by slovenianGooner** [comment]
Sorry, forgot to mention it specifically but the screenshots are from codecourse, the fixes are for both codecourse and codecourse-contrast.

Hm, not sure, but I downloaded the .jar file and in the .xml the color is #000000.

**Comment by daylerees** [comment]
Woop, you're right it's broken in that release. 🤦‍♂️  I'll try to get a fix out.

**Comment by daylerees** [comment]
Solved this in `1.5.1` (you'll need the jar). Thanks for bringing this to my attention! :)

**Pull request closed without merging**
